### ISSUE TITLE
Update Portfolio page

### ISSUE THREAD

**Issue by iteles** [foundersandcoders/oursite#274]
Currently the 'Founders' page and needs to be updated.
Text and links can be found:
https://docs.google.com/document/d/1a1QCi_9FhIB0HaVlIqsccM3EFDOvfoCuBuoPgb8rOs8/edit#heading=h.kdttwuv1xcud

<hr/>

This is part of a larger [content refactor](https://github.com/foundersandcoders/oursite/milestone/1), led by @rebeccaradding, I'm translating the [proposed content doc](https://docs.google.com/document/d/1a1QCi_9FhIB0HaVlIqsccM3EFDOvfoCuBuoPgb8rOs8/edit?usp=sharing) into issues so action can be taken.

**Comment by franzmoro** [comment]
ok, so this is what I've understood:
## Tasks
- [x] Delete previous page content
- [x] Change Nav link "Founders" --> "Portfolio"
- [x] Insert text paragraph
- [x] Download (in better res) logos and insert them in 3-by-3 rows
